export enum newsActions {
  LOAD_NEWS_REQUEST = '@@NEWS/LOAD_NEWS_REQUEST',
  LOAD_NEWS_SUCCESS = '@@NEWS/LOAD_NEWS_SUCCESS',
  LOAD_NEWS_FAILURE = '@@NEWS/LOAD_NEWS_FAILURE',
  GET_NEWS = '@@NEWS/GET_NEWS',
}

export enum cryptoActions  {
  LOAD_CRYPTO_REQUEST = '@@CRYPTO/LOAD_CRYPTO_REQUEST',
  LOAD_CRYPTO_SUCCESS = '@@CRYPTO/LOAD_CRYPTO_SUCCESS',
  LOAD_CRYPTO_FAILURE = '@@CRYPTO/LOAD_CRYPTO_FAILURE',
  GET_CRYPTO_PRICE = '@@CRYPTO/GET_CRYPTO_PRICE',
  LOAD_CRYPTO_HISTORY_REQUEST = '@@CRYPTO/LOAD_CRYPTO_HISTORY_REQUEST',
  LOAD_CRYPTO_HISTORY_SUCCESS = '@@CRYPTO/LOAD_CRYPTO_HISTORY_SUCCESS',
  LOAD_CRYPTO_HISTORY_FAILURE = '@@CRYPTO/LOAD_CRYPTO_HISTORY_FAILURE',
};

export const getNews = () => ({
  type: newsActions.GET_NEWS
} as const)

export const getCryptoPrice = () => ({
  type: cryptoActions.GET_CRYPTO_PRICE
}) 

export type newsACTypes = ReturnType<typeof getNews>
